#!/usr/bin/env bash
# Shared by every script that starts and stops a server. Sourced, never executed, and so it
# sets no shell options: `set -euo pipefail` here would leak into whatever sourced it. Every
# caller sets them itself, and `make check` holds both halves of that to the file mode.
#
# These four functions were copied into four scripts and had already drifted into four
# different answers to the same two traps, which is exactly the failure a second home for a
# fact produces. Both traps are in docs/TECH.md, and neither may be re-solved locally.

# ENDPOINT and PROC are what a caller overrides; the defaults are this project's server.
ENDPOINT="${ENDPOINT:-http://127.0.0.1:8081}"
PROC="${PROC:-llama-server}"

# HEALTH_GRACE is the trap. A serve script validates its config and only then execs the
# server, so for the first instants after launch there is nothing for pgrep to find. Without
# the grace the first poll — curl refused in a millisecond, pgrep finding nothing — reports
# "load failed" for a server that goes on to load in 15 s. It fires only on a loaded machine,
# where the child is slow to be scheduled, which is when the measurement matters.
HEALTH_GRACE="${HEALTH_GRACE:-20}"

# server_alive reports whether the server this run started is still there. Overridable,
# because a runtime that sets its own process title cannot be found by pattern — MTPLX's
# command line is just the Python binary — and is tracked by pid instead.
server_alive() { pgrep -f "$PROC" >/dev/null; }

# stop_server ends it and waits for the memory back. The trap: an 18 GB process does not
# exit on a fixed sleep, and the next server binding while the old one still holds the port
# measures the previous config under the next config's name.
#
# STOP_CMD gives a runtime with a stop command of its own the chance to use it first.
stop_server() {
  if [ -n "${STOP_CMD:-}" ]; then eval "$STOP_CMD" >/dev/null 2>&1 || true; fi
  pkill -f "$PROC" 2>/dev/null || true
  local deadline=$((SECONDS + 90))
  while pgrep -f "$PROC" >/dev/null; do
    [ $SECONDS -ge $deadline ] && { pkill -9 -f "$PROC" 2>/dev/null || true; sleep 3; break; }
    sleep 1
  done
  sleep 2
}

# wait_healthy <seconds>: 0 once the endpoint answers, 1 if it died or the wait ran out.
# llama-server answers 503 while it loads and 200 when it can serve, so the code is the
# readiness signal and the body is not read.
wait_healthy() {
  local deadline=$((SECONDS + $1)) grace=$((SECONDS + HEALTH_GRACE))
  while [ $SECONDS -lt $deadline ]; do
    [ "$(curl -s -m 2 -o /dev/null -w '%{http_code}' "$ENDPOINT/health" 2>/dev/null)" = "200" ] && return 0
    if [ $SECONDS -ge $grace ] && ! server_alive; then return 1; fi
    sleep 3
  done
  return 1
}

# served_ctx asks the endpoint what it is serving, and prints `null` for a backend that does
# not say. The guard against measuring one config under another's name, so a caller that
# skips it is claiming rather than checking.
served_ctx() {
  curl -s -m 5 "$ENDPOINT/props" 2>/dev/null \
    | python3 -c "import sys,json;print(json.load(sys.stdin)['default_generation_settings']['n_ctx'])" 2>/dev/null \
    || echo null
}

# desk_baseline prints the compositor's rate in cores before any model is loaded. Per run,
# because the machine's baseline is not a constant and a desktop verdict has to carry the
# basis it was judged against.
desk_baseline() {
  local a b
  a=$(./scripts/deskprobe.sh); sleep 6; b=$(./scripts/deskprobe.sh)
  A="$a" B="$b" python3 -c "
import json, os
a, b = json.loads(os.environ['A']), json.loads(os.environ['B'])
span = b['t'] - a['t']
print(round((b['windowserver_cpu_seconds'] - a['windowserver_cpu_seconds']) / span, 3) if span > 0 else 0)"
}

# cell_config writes one ladder cell: a base serving config with the context and KV type
# this rung is asking about. Generated rather than committed, because a rung written by hand
# is a fact about one machine — the defect docs/VISION.md names first.
cell_config() { # base ctx kv out
  local base="$1" ctx="$2" kv="$3" out="$4"
  # The base's comments are dropped, not carried: they describe the base's context and KV
  # type, and a generated file explaining itself as something else is worse than one that
  # says nothing. Settings only, then this rung's two.
  {
    printf '# Generated by scripts/ladder.sh from %s. Not committed: a rung is derived.\n' "$base"
    grep -E '^[A-Z_]+=' "$base" | grep -vE '^(CTX_SIZE|CACHE_TYPE_K|CACHE_TYPE_V)='
    printf 'CTX_SIZE="%s"\nCACHE_TYPE_K="%s"\nCACHE_TYPE_V="%s"\n' "$ctx" "$kv" "$kv"
  } > "$out"
}
